services:


  nginx:

    image: nginx:latest

    container_name: minicomm-nginx

    restart: unless-stopped


    ports:

      - "80:80"


    volumes:

      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro


    depends_on:

      - ordering-api
      - inventory-api


    networks:

      - minicomm-network
  ordering-db:

    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: ordering-sqlserver

    restart: unless-stopped

    environment:

      ACCEPT_EULA: "Y"

      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}


    ports:

      - "14331:1433"


    volumes:

      - ordering-db-data:/var/opt/mssql


    healthcheck:

      test:
        [
          "CMD-SHELL",
          "timeout 5 bash -c '</dev/tcp/127.0.0.1/1433'"
        ]

      interval: 10s

      timeout: 5s

      retries: 20


    networks:

      - minicomm-network





  inventory-db:

    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: inventory-sqlserver

    restart: unless-stopped


    environment:

      ACCEPT_EULA: "Y"

      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}


    ports:

      - "14332:1433"


    volumes:

      - inventory-db-data:/var/opt/mssql


    healthcheck:

      test:
        [
          "CMD-SHELL",
          "timeout 5 bash -c '</dev/tcp/127.0.0.1/1433'"
        ]

      interval: 10s

      timeout: 5s

      retries: 20


    networks:

      - minicomm-network





  rabbitmq:

    image: rabbitmq:3-management

    container_name: minicomm-rabbitmq

    restart: unless-stopped


    environment:

      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}

      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}


    ports:

      - "5672:5672"

      - "15672:15672"


    healthcheck:

      test:
        [
          "CMD",
          "rabbitmq-diagnostics",
          "ping"
        ]

      interval: 10s

      timeout: 5s

      retries: 10


    networks:

      - minicomm-network





  redis:

    image: redis:7

    container_name: minicomm-redis

    restart: unless-stopped


    ports:

      - "6379:6379"


    networks:

      - minicomm-network





  ordering-api:

    image: minicommerce-ordering

    container_name: ordering-api

    restart: unless-stopped


    ports:

      - "8080:8080"


    environment:

      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}


      ConnectionStrings__OrderingConnection: "Server=ordering-db;Database=MiniCommerce.Ordering;User Id=sa;Password=${MSSQL_PASSWORD};TrustServerCertificate=True"


      RabbitMQ__Host: rabbitmq

      RabbitMQ__VirtualHost: /

      RabbitMQ__Username: ${RABBIT_USERNAME}

      RabbitMQ__Password: ${RABBIT_PASSWORD}


    depends_on:

      ordering-db:

        condition: service_healthy


      rabbitmq:

        condition: service_healthy


    networks:

      - minicomm-network





  inventory-api:

    image: minicommerce-inventory

    container_name: inventory-api

    restart: unless-stopped


    ports:

      - "8081:8080"


    environment:

      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}


      ConnectionStrings__InventoryConnection: "Server=inventory-db;Database=MiniCommerce.Inventory;User Id=sa;Password=${MSSQL_PASSWORD};TrustServerCertificate=True"


      RabbitMQ__Host: rabbitmq

      RabbitMQ__VirtualHost: /

      RabbitMQ__Username: ${RABBIT_USERNAME}

      RabbitMQ__Password: ${RABBIT_PASSWORD}


    depends_on:

      inventory-db:

        condition: service_healthy


      rabbitmq:

        condition: service_healthy


    networks:

      - minicomm-network





volumes:

  ordering-db-data:

  inventory-db-data:





networks:

  minicomm-network:

    name: minicomm-network

    driver: bridge