name: MiniCommerce CI


on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  build:


    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x


      - name: Restore dependencies
        run: dotnet restore MiniCommerce.sln


      - name: Build solution
        run: dotnet build MiniCommerce.sln --no-restore --configuration Release


      - name: Test
        run: |
          dotnet test MiniCommerce.sln \
          --no-build \
          --configuration Release \
          --logger "console;verbosity=detailed" \
          --logger "trx;LogFileName=test-results.trx"


      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/*.trx"