name: Docker Build and Push


on:
  push:
    branches:
      - main


permissions:
  contents: read
  packages: write


jobs:

  docker-build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        include:
          - name: ordering-api
            dockerfile: Ordering.API/Dockerfile

          - name: inventory-api
            dockerfile: Inventory.API/Dockerfile

          - name: payment-api
            dockerfile: Payment.API/Dockerfile

          - name: shipping-api
            dockerfile: Shipping.API/Dockerfile

          - name: fault-monitoring-worker
            dockerfile: FaultMonitoring.Worker/Dockerfile

          - name: database-migrator
            dockerfile: MiniCommerce.DatabaseMigrator/Dockerfile


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Image
        run: |
          IMAGE=ghcr.io/sinasabet/minicommerce-${{ matrix.name }}
          IMAGE_TAG=${{ github.sha }}

          docker build \
          -f ${{ matrix.dockerfile }} \
          -t $IMAGE:latest \
          -t $IMAGE:$IMAGE_TAG .


      - name: Push Image
        run: |
          IMAGE=ghcr.io/sinasabet/minicommerce-${{ matrix.name }}
          IMAGE_TAG=${{ github.sha }}

          docker push $IMAGE:latest
          docker push $IMAGE:$IMAGE_TAG
